### PR TITLE
WIP: Refactor for use with Puppet 5

### PR DESCRIPTION
**Pull request by poikilotherm**
Hey guys,

I just started work to make this module "future ready".
Would be glad if you could have a look and comment... :-)

[Build Status](https://travis-ci.org/poikilotherm/puppet-uwsgi-wip)

TODOs:
- [x] On RedHat optionally include EPEL module (needed for pip and/or uwsgi packages), add dependency to metadata.json
- [x] Install uwsgi on Debian from package repos instead of pip (maybe exclude old Ubuntu/Debian versions or at least check - old versions in repos for these!)
- [x] Acceptance testing with Beaker-RSpec for all supported platforms excluding RedHat 6+7 (use CentOS only) with default parameters
- [x] Add TravisCI for Rubocop, Lint (Puppet + Metadata), Rspec, Beaker-Rspec
- [x] Repair Debian 7 support: module uses Upstart init script which is unusable on Debian 7
- [x] When installing via pip, use `mkdir -p` for $app_directory
- [x] Include fix for #21 
- [ ] ~~Acceptance testing for (forced) installation via pip~~
- [x] Enable installation of plugin packages from distro repos
- [x] Documentation update of README to reflect new structure and limitations

Cheers
Oliver

### CODE REVIEW

**Comment by poikilotherm** [comment]
Hi @jarshwah and @rvdh,

I really would appreciate comments on this - do you agree on this and would you like me to go forward?

Cheers,
Oliver

**Comment by jarshwah** [comment]
Just FYI I'm not involved with this project anymore - and don't use puppet anymore so I can't provide any feedback here unfortunately.

**Comment by poikilotherm** [comment]
Ok, thanks for the info.

@rvdh: would you like to transfer the ownership - you seemed to seek for a maintainer...

**Comment by rvdh** [comment]
@poikilotherm I wasn't looking for a maintainer, that was @jarshwah :)
I appreciate the effort you're making with this! I hope to have some time soon to look into this in detail.

**Comment by rvdh** [comment]
@poikilotherm I've been thinking about this and since I will not have much time to maintain this module, I don't mind transferring it to you. If you rename your own puppet-uwsgi repository I can initiate the transfer.

**Comment by poikilotherm** [comment]
Sure, no problem. (Done...)

As I am planning to release a new version to the forge, could you guys @rvdh and @jarshwah delete your modules from the forge so people don't get confused by three different releases?

I would re-release the old versions and give credit for them... 

Cheers
Oliver

**Comment by rvdh** [comment]
@poikilotherm When your module is published, I'll update the README of my own to redirect users to your module. After a while I can remove the module alltogether, but if I do that immediately users with references to it in their r10k Puppetfiles will get errors.

**Comment by poikilotherm** [comment]
Oh, I thought that would be transparent for r10k users..
https://docs.puppet.com/puppet/latest/modules_publishing.html#delete-a-module-release-from-the-forge

**Comment by rvdh** [comment]
The way I understand it is that deleted *releases* will remain available for download. Not sure that also applies to removing modules completely.

**Comment by poikilotherm** [comment]
We are getting nearer... Will test this now on some real stuff and see how it goes.

**Comment by poikilotherm** [comment]
Hi @rvdh,

I just released my module to the forge: https://forge.puppet.com/poikilotherm/uwsgi

I'll close this PR, maybe you can initiate the transfer?

It would be great if you release a version 999.999.999 to the forge with your hint to the new repo :-)

Cheers
Oliver

**Pull request closed without merging**
